export const FETCH_SEARCH_RESTAURANTS_PENDING = 'FETCH_SEARCH_RESTAURANTS_PENDING';
export const FETCH_SEARCH_RESTAURANTS_SUCCESS = 'FETCH_SEARCH_RESTAURANTS_SUCCESS';
export const FETCH_SEARCH_RESTAURANTS_FAIL = 'FETCH_SEARCH_RESTAURANTS_FAIL';

export const GET_RESTAURANT_DETAIL_PENDING = 'GET_RESTAURANT_DETAIL_PENDING';
export const GET_RESTAURANT_DETAIL_SUCCESS = 'GET_RESTAURANT_DETAIL_SUCCESS';
export const GET_RESTAURANT_DETAIL_FAIL = 'GET_RESTAURANT_DETAIL_FAIL';