export const FETCH_SEARCH_RESTAURANTS_PENDING = 'FETCH_SEARCH_RESTAURANTS_PENDING';
export const FETCH_SEARCH_RESTAURANTS_SUCCESS = 'FETCH_SEARCH_RESTAURANTS_SUCCESS';
export const FETCH_SEARCH_RESTAURANTS_FAIL = 'FETCH_SEARCH_RESTAURANTS_FAIL';